# Generated by Django 4.2.27 on 2026-06-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
